"""Pull the current template library from the ThemeZap site into this page.

    python sync.py

Reads ../themezap/src/content/products.ts and bundle.ts, then:
  - rewrites covers/ with one 480px webp per live template (stale ones removed)
  - rewrites covers.js with the slug list
  - updates the template count and bundle price between the <!--tz:...--> markers
    in index.html

Covers stay at 480px on purpose: the wall shows ~100 of them at once and full-size
covers run a phone out of GPU memory, leaving the tiles blank.
"""
import json
import re
from pathlib import Path

from PIL import Image

HERE = Path(__file__).parent
SITE = HERE.parent / "themezap"
WIDTH = 480


def live_templates():
    src = (SITE / "src/content/products.ts").read_text(encoding="utf8")
    body = src.split("export const products")[1].split("export function")[0]
    out = []
    for block in re.split(r"\n  \{\n", body)[1:]:
        field = lambda k: (re.search(k + r':\s*"([^"]+)"', block) or [None, None])[1]
        if field("type") != "templates" or field("status") in ("hidden", "coming-soon"):
            continue
        image = field("image")
        if image and (SITE / "public" / image.lstrip("/")).exists():
            out.append((field("slug"), SITE / "public" / image.lstrip("/")))
    return out


def bundle_price():
    src = (SITE / "src/content/bundle.ts").read_text(encoding="utf8")
    return int(re.search(r"price:\s*(\d+)", src)[1])


def main():
    templates = live_templates()
    price = bundle_price()

    covers = HERE / "covers"
    covers.mkdir(exist_ok=True)
    keep = set()
    for slug, path in templates:
        im = Image.open(path).convert("RGB")
        if im.width > WIDTH:
            im = im.resize((WIDTH, round(im.height * WIDTH / im.width)), Image.LANCZOS)
        im.save(covers / f"{slug}.webp", "WEBP", quality=78, method=6)
        keep.add(f"{slug}.webp")
    for stale in covers.glob("*.webp"):
        if stale.name not in keep:
            stale.unlink()

    slugs = [s for s, _ in templates]
    (HERE / "covers.js").write_text(
        "// Generated by sync.py — do not edit by hand.\n"
        f"window.TZ_COVERS = {json.dumps(slugs)};\n",
        encoding="utf8",
    )

    html_path = HERE / "index.html"
    html = html_path.read_text(encoding="utf8")
    html = re.sub(r"(<!--tz:count-->).*?(<!--/tz-->)", rf"\g<1>{len(slugs)}\g<2>", html)
    html = re.sub(r"(<!--tz:price-->).*?(<!--/tz-->)", rf"\g<1>${price}\g<2>", html)
    html_path.write_text(html, encoding="utf8")

    print(f"{len(slugs)} templates, bundle ${price}")


if __name__ == "__main__":
    main()
